// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teste_de_conhecimento_Campos_Dealer.Data;

#nullable disable

namespace Teste_de_conhecimento_Campos_Dealer.Migrations
{
    [DbContext(typeof(AppBdContext))]
    [Migration("20240711125051_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dathVenda")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dscProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("vlrUnitário")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("clienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dathVenda")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("produtoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("qtdVenda")
                        .HasColumnType("int");

                    b.Property<int>("vlrTotalVenda")
                        .HasColumnType("int");

                    b.Property<int>("vlrUnitarioVenda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("produtoId");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Venda", b =>
                {
                    b.HasOne("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teste_de_conhecimento_Campos_Dealer.Models.Entities.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
